param(
    [switch]$Nightly,
    [switch]$Debug,
    [switch]$NoGui,
    [switch]$NoIntegrate
)

$ErrorActionPreference = "Stop"

if ($env:NIGHTLY -and $env:NIGHTLY -ne "0") { $Nightly = $true }
if ($env:DEBUG -and $env:DEBUG -ne "0") { $Debug = $true }
if ($env:NO_GUI -and $env:NO_GUI -ne "0") { $NoGui = $true }
if ($env:NO_INTEGRATE -and $env:NO_INTEGRATE -ne "0") { $NoIntegrate = $true }
# debug builds are only published for nightlies
if ($Debug) { $Nightly = $true }
if ($NoGui) { $NoIntegrate = $true }

if ($Nightly) {
    $repo = "neurocyte/flow-nightly"
    $title = "flow nightly build"
} else {
    $repo = "neurocyte/flow"
    $title = "flow"
}
if ($Debug) {
    $title = "$title (debug)"
}

$release = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/releases/latest"
$version = $release.tag_name
$title_updater = "$title updater"
$install_dir = "$env:APPDATA\flow\bin"

$existing_flow = Join-Path -Path $install_dir -ChildPath "flow.exe"
if (Test-Path $existing_flow) {
    $existing_version_output = & $existing_flow --version 2>&1 | Out-String
    $existing_version_lines = $existing_version_output -split "[\r\n]+" | Where-Object { $_ -match '^\s*version:\s*(.+?)\s*$' }
    if ($existing_version_lines -and $matches) {
        $existing_version = $matches[1]
        if ($version -eq $existing_version) {
            Write-Host "$title is up-to-date (version $version @ $install_dir)"
            return
        }
    }
}

$title = "$title $version"

switch ($env:PROCESSOR_ARCHITECTURE) {
    "AMD64"  { $arch = "x86_64" }
    "ARM64"  { $arch = "aarch64" }
    default  {
        Write-Host "unknown architecture: $($env:PROCESSOR_ARCHITECTURE)"
        $LASTEXITCODE = 1
        return
    }
}

$filename = "flow-$version-windows-$arch"
if ($Debug) {
    $filename = "$filename-debug"
}
$filename = "$filename.zip"

if (-not (Test-Path $install_dir)) {
    Write-Host "creating installation directory: $install_dir"
    New-Item -ItemType Directory -Path $install_dir | Out-Null
}

Write-Host "downloading $title..."
Invoke-WebRequest -Uri "https://github.com/$repo/releases/download/$version/$filename" -OutFile "$install_dir\$filename"

echo "installing $title to $install_dir ..."
$stage = Join-Path $env:TEMP "flow-install-$([System.Guid]::NewGuid().ToString('N'))"
Expand-Archive -Path "$install_dir\$filename" -DestinationPath $stage -Force
Remove-Item "$install_dir\$filename"

$staged_gui = Join-Path $stage "flow-gui.exe"
if ($NoGui) {
    Remove-Item $staged_gui -Force -ErrorAction SilentlyContinue
} elseif (-not (Test-Path $staged_gui)) {
    Write-Host "note: this build does not include flow-gui"
    $NoIntegrate = $true
}

Copy-Item (Join-Path $stage "*") $install_dir -Recurse -Force
Remove-Item $stage -Recurse -Force

if (-not $NoIntegrate) {
    $gui = Join-Path $install_dir "flow-gui.exe"
    $programs = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs"
    $shortcut_path = Join-Path $programs "Flow Control.lnk"
    $shortcut = (New-Object -ComObject WScript.Shell).CreateShortcut($shortcut_path)
    $shortcut.TargetPath = $gui
    $shortcut.WorkingDirectory = $install_dir
    $shortcut.Description = "Flow Control"
    $shortcut.Save()
    Write-Host "created start menu shortcut $shortcut_path"
}

echo "installing $title_updater to $install_dir\update-flow.ps1 ..."
Invoke-WebRequest -Uri "https://flow-control.dev/install.ps1" -OutFile "$install_dir\install.ps1"
# update-flow repeats this install with the same options, so that updating a
# nightly does not silently switch to a release
$switches = @()
if ($Nightly) { $switches += "-Nightly" }
if ($Debug) { $switches += "-Debug" }
if ($NoGui) { $switches += "-NoGui" } elseif ($NoIntegrate) { $switches += "-NoIntegrate" }
$updater_script = @"
# generated by the flow installer
& "`$PSScriptRoot\install.ps1" $($switches -join ' ')
"@
Set-Content -Path "$install_dir\update-flow.ps1" -Value $updater_script

echo "$title installed successfully to $install_dir"

$current_path = [System.Environment]::GetEnvironmentVariable("Path", "User")
if ($current_path -notlike "*$install_dir*") {
    $response = Read-Host "do you want to add $install_dir to your PATH? (y/n)"
    if ($response -eq "y") {
        $newPath = "$current_path;$install_dir"
        [System.Environment]::SetEnvironmentVariable("Path", $newPath, "User")
        Write-Host "added $install_dir to PATH"
        Write-Host "close your terminal for changes to take effect"
    }
}
